services:
  timescaledb:
    image: timescale/timescaledb:2.18.1-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
    networks:
      - racing-coach-network

  racing-coach-server:
    build:
      context: ./apps/racing-coach-server
      dockerfile: Dockerfile
    container_name: racing-coach-server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@timescaledb:5432/postgres
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - racing-coach-network

  racing-coach-web:
    build:
      context: ./apps/racing-coach-web
      dockerfile: Dockerfile
    container_name: racing-coach-web
    ports:
      - "3000:80"
    depends_on:
      - racing-coach-server
    restart: unless-stopped
    networks:
      - racing-coach-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: racing_telemetry_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - racing-coach-network

networks:
  racing-coach-network:
    driver: bridge